In [3]:
import numpy as np

In [7]:
a = np.array([[1,-3,3],
            [3,-5,3],
            [6,-6,4]])
a

array([[ 1, -3,  3],
       [ 3, -5,  3],
       [ 6, -6,  4]])

In [11]:
w,v = np.linalg.eig(a)
print(w)
print(v)


[ 4. -2. -2.]
[[-0.40824829 -0.81034214  0.1932607 ]
 [-0.40824829 -0.31851537 -0.59038328]
 [-0.81649658  0.49182677 -0.78364398]]
