# 75 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.version

<module 'numpy.version' from 'C:\\Users\\Ana\\Anaconda3\\envs\\Ana1\\lib\\site-packages\\numpy\\version.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
x = np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
x.nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
y = np.zeros(10)
y[4] = 1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
y = np.arange(10,50)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [13]:
y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [36]:
x = np.array([1,2,0,0,4,0])
x.nonzero()



(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [38]:
np.random.normal(size=(3,3,3))

array([[[-0.03308468,  0.1287485 ,  0.07982202],
        [-0.46850628, -1.13305958,  1.41985192],
        [ 0.50749103,  0.6898338 , -0.062842  ]],

       [[ 1.33716951, -0.68661872, -1.87328545],
        [ 0.02981413,  0.13954448,  0.12416545],
        [ 0.10119578,  1.09292346,  1.26337922]],

       [[-0.58533304, -0.11510262, -0.72029208],
        [ 0.32083404,  1.29361904, -0.28159922],
        [-0.97441128,  0.76778661,  1.74935187]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [41]:
y = np.random.normal(size=(10,10))
z = y.min(), y.max()
z

(-2.19783397250769, 2.186691267452452)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [43]:
np.mean(np.random.normal(size=30))

0.042606240469557126

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [81]:
np.array([[1,0],[0,1]])

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [47]:
np.pad(np.array([[1,0],[0,1]]),1,mode="constant")

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [87]:
(np.arange(25).reshape(5,5)).T

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [91]:
x = (np.zeros(64).reshape(8,8)).T

x[1::2,::2]=1
x[::2,1::2]=1

x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [94]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [135]:
x = np.zeros(8).reshape(2,4)
x[::2,1::2]=1
x[1::2,::2]=1
np.tile(x,(4,2))

np.tile(np.array([[0,1],[1,0]]),(4,4) )


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [129]:
x = np.random.normal(size=25).reshape(5,5)
x

n= (x - x.min())/(x.max() - x.min())
n

array([[0.1452176 , 0.47010406, 1.        , 0.42344597, 0.86152335],
       [0.07072033, 0.34602489, 0.69505262, 0.78727311, 0.33151896],
       [0.49418363, 0.64972863, 0.11816149, 0.3505607 , 0.75461752],
       [0.644541  , 0.52460381, 0.86497599, 0.58646789, 0.3414215 ],
       [0.16234746, 0.71279058, 0.        , 0.92999926, 0.53979606]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [145]:
x = np.arange(0,15).reshape(5,3)
y = np.arange(0,6).reshape(3,2)

print (x)
print(y)

z= x.dot(y)


np.dot(x,y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [146]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [147]:
x = np.arange(15)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [152]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [153]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Ana\Anaconda3\envs\Ana1\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Ana\Anaconda3\envs\Ana1\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [154]:
np.ceil(1.5)

2.0

#### 30. How to find common values between two arrays? (★☆☆)

In [157]:
a=np.array([1,2])
b=np.array([1,3])
x = np.intersect1d(a,b)
x

array([1])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [162]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
Z

# Back to sanity
_ = np.seterr(**defaults)
Z

array([inf])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [164]:
np.emath.sqrt(-1)
#Return the non-negative square-root of an array, element-wise.


1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [169]:
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')


numpy.datetime64('2019-10')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [177]:
jul16 = np.arange('2016-07','2016-08',dtype='datetime64[D]')
jul16

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [196]:
# ( (A+B) * (-A/2) ) in place?

a = np.ones(3)*2
b = np.ones(3)*2
c = np.ones(3)*5
result=[]

np.add(a,b,out=b)
np.negative(a,out=a)
np.divide(a,2,out=a)
np.multiply(a,b,out=c)
print(c)



[-4. -4. -4.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [213]:


x = np.random.normal(0,1,10)

x = x[x.astype(int)==True]
x.astype(int)
print (np.trunc(x))
print (x - x%1)
print (np.floor(x))
print (np.ceil(x))




[-2. -2. -0. -1. -0. -0. -0. -1. -0. -2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [217]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. Consider two random array A and B, check if they are equal (★★☆)

#### 42. Make an array immutable (read-only) (★★☆)

#### 43. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 44. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 45. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

#### 46. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 47. How to print all the values of an array? (★★☆)

#### 48. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 49. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 50. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 51. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 52. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 53. Generate a generic 2D Gaussian-like array (★★☆)

#### 54. How to randomly place p elements in a 2D array? (★★☆)

#### 55. Subtract the mean of each row of a matrix (★★☆)

#### 56. How to sort an array by the nth column? (★★☆)

#### 57. How to tell if a given 2D array has null columns? (★★☆)

#### 58. Find the nearest value from a given value in an array (★★☆)

#### 59. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 60. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 61. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 62. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 63. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 64. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 65. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 66. How to swap two rows of an array? (★★★)

#### 67. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 68. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 69. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 70. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 71. How to find the most frequent value in an array?

#### 72. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 73. How to get the n largest values of an array (★★★)

#### 74. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 75. Convert a vector of ints into a matrix binary representation (★★★)