# 75 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.version

<module 'numpy.version' from 'C:\\Users\\Ana\\Anaconda3\\envs\\Ana1\\lib\\site-packages\\numpy\\version.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
x = np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
x.nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
y = np.zeros(10)
y[4] = 1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
y = np.arange(10,50)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [13]:
y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [36]:
x = np.array([1,2,0,0,4,0])
x.nonzero()



(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [38]:
np.random.normal(size=(3,3,3))

array([[[-0.03308468,  0.1287485 ,  0.07982202],
        [-0.46850628, -1.13305958,  1.41985192],
        [ 0.50749103,  0.6898338 , -0.062842  ]],

       [[ 1.33716951, -0.68661872, -1.87328545],
        [ 0.02981413,  0.13954448,  0.12416545],
        [ 0.10119578,  1.09292346,  1.26337922]],

       [[-0.58533304, -0.11510262, -0.72029208],
        [ 0.32083404,  1.29361904, -0.28159922],
        [-0.97441128,  0.76778661,  1.74935187]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [41]:
y = np.random.normal(size=(10,10))
z = y.min(), y.max()
z

(-2.19783397250769, 2.186691267452452)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [43]:
np.mean(np.random.normal(size=30))

0.042606240469557126

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [81]:
np.array([[1,0],[0,1]])

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [47]:
np.pad(np.array([[1,0],[0,1]]),1,mode="constant")

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [87]:
(np.arange(25).reshape(5,5)).T

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [91]:
x = (np.zeros(64).reshape(8,8)).T

x[1::2,::2]=1
x[::2,1::2]=1

x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [94]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [135]:
x = np.zeros(8).reshape(2,4)
x[::2,1::2]=1
x[1::2,::2]=1
np.tile(x,(4,2))

np.tile(np.array([[0,1],[1,0]]),(4,4) )


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [129]:
x = np.random.normal(size=25).reshape(5,5)
x

n= (x - x.min())/(x.max() - x.min())
n

array([[0.1452176 , 0.47010406, 1.        , 0.42344597, 0.86152335],
       [0.07072033, 0.34602489, 0.69505262, 0.78727311, 0.33151896],
       [0.49418363, 0.64972863, 0.11816149, 0.3505607 , 0.75461752],
       [0.644541  , 0.52460381, 0.86497599, 0.58646789, 0.3414215 ],
       [0.16234746, 0.71279058, 0.        , 0.92999926, 0.53979606]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [145]:
x = np.arange(0,15).reshape(5,3)
y = np.arange(0,6).reshape(3,2)

print (x)
print(y)

z= x.dot(y)


np.dot(x,y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [146]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [147]:
x = np.arange(15)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [152]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [153]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Ana\Anaconda3\envs\Ana1\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Ana\Anaconda3\envs\Ana1\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [154]:
np.ceil(1.5)

2.0

#### 30. How to find common values between two arrays? (★☆☆)

In [157]:
a=np.array([1,2])
b=np.array([1,3])
x = np.intersect1d(a,b)
x

array([1])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [162]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
Z

# Back to sanity
_ = np.seterr(**defaults)
Z

array([inf])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [164]:
np.emath.sqrt(-1)
#Return the non-negative square-root of an array, element-wise.


1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [169]:
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')


numpy.datetime64('2019-10')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [177]:
jul16 = np.arange('2016-07','2016-08',dtype='datetime64[D]')
jul16

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [196]:
# ( (A+B) * (-A/2) ) in place?

a = np.ones(3)*2
b = np.ones(3)*2
c = np.ones(3)*5
result=[]

np.add(a,b,out=b)
np.negative(a,out=a)
np.divide(a,2,out=a)
np.multiply(a,b,out=c)
print(c)



[-4. -4. -4.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [213]:


x = np.random.normal(0,1,10)

x = x[x.astype(int)==True]
x.astype(int)
print (np.trunc(x))
print (x - x%1)
print (np.floor(x))
print (np.ceil(x))




[-2. -2. -0. -1. -0. -0. -0. -1. -0. -2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [217]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [3]:
def int_gen():
    for x in range(10):
        yield x
        
x = np.fromiter(int_gen(), dtype = int, count = -1)
print(x)



[0 1 2 3 4 5 6 7 8 9]


In [ ]:


np.fromfunction(lambda i, j: i+j, (5, 2), dtype=np.int8)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [5]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
z=np.random.normal(1,10,3)
z.sort()
z

array([-8.58421853,  1.93230343, 15.26844599])

#### 41. Consider two random array A and B, check if they are equal (★★☆)

In [15]:
z =np.random.normal(1,3,3)
x=np.random.normal(1,3,3)
np.array_equal(z,x)

False

#### 42. Make an array immutable (read-only) (★★☆)

In [ ]:
x = np.random.uniform(0,10,10)
x.flags.writeable = False
x[1]=3

#### 43. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [16]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.65397805 1.04801422 0.99204718 1.06717862 1.0898483  1.2886211
 0.9128214  0.88173853 0.8341931  1.12418059]
[1.51801157 0.88631119 0.04530085 1.09044592 0.90166469 0.72224045
 0.46543005 0.41509054 0.4761955  0.67687235]


#### 44. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [17]:
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.98257541 0.35436139 0.73770322 0.06054554 0.94083431 0.84961913
 0.56318317 0.62080045 0.54260034 0.24838083]
[0.         0.35436139 0.73770322 0.06054554 0.94083431 0.84961913
 0.56318317 0.62080045 0.54260034 0.24838083]


#### 45. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [20]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 46. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [23]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 47. How to print all the values of an array? (★★☆)

In [30]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 48. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [45]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])
print(Z)
print(v)

51
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
51.45849057130626


#### 49. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [50]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)


[[0.         1.04855341 0.33648588 0.89596271 1.01332232 0.61368033
  0.08381316 0.2052859  0.87381829 0.58973428]
 [1.04855341 0.         0.85667615 0.7145369  0.77308849 0.49899117
  1.00064555 1.02389636 0.19487347 0.91147809]
 [0.33648588 0.85667615 0.         0.56157287 0.67765709 0.56045051
  0.25327622 0.18970302 0.66370299 0.27210898]
 [0.89596271 0.7145369  0.56157287 0.         0.12106812 0.7908919
  0.8138541  0.73796463 0.56262987 0.38061997]
 [1.01332232 0.77308849 0.67765709 0.12106812 0.         0.90048249
  0.93069305 0.84970396 0.64101733 0.47572362]
 [0.61368033 0.49899117 0.56045051 0.7908919  0.90048249 0.
  0.59141291 0.66398068 0.38837804 0.75469122]
 [0.08381316 1.00064555 0.25327622 0.8138541  0.93069305 0.59141291
  0.         0.13339095 0.82018698 0.50662116]
 [0.2052859  1.02389636 0.18970302 0.73796463 0.84970396 0.66398068
  0.13339095 0.         0.83473076 0.3985807 ]
 [0.87381829 0.19487347 0.66370299 0.56262987 0.64101733 0.38837804
  0.82018698 0.834730

In [ ]:

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

#### 50. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
z = np.arange(10, dtype=np.float32)
z = z.astype(np.int32, copy=False)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#### 51. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 52. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [61]:
Z = np.arange(9).reshape(3,3)
for index, x in np.ndenumerate(Z):
    print(index, x)
    
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 53. Generate a generic 2D Gaussian-like array (★★☆)

In [62]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
G = np.exp(
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 54. How to randomly place p elements in a 2D array? (★★☆)

In [78]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 55. Subtract the mean of each row of a matrix (★★☆)

In [83]:
# Author: Warren Weckesser

x = np.random.rand(5, 10)
print(x)
# Recent versions of numpy
y = x - x.mean(axis=1, keepdims=True)


print(y)

[[0.98975976 0.53738588 0.05241126 0.37815133 0.93783965 0.65411964
  0.19261535 0.48322509 0.47123942 0.08563184]
 [0.70389939 0.8922691  0.23189785 0.6330996  0.66579168 0.54819013
  0.17062402 0.65475013 0.51785154 0.31347022]
 [0.05341019 0.25237372 0.67846817 0.30509885 0.25617103 0.37609726
  0.61407431 0.26307771 0.42532656 0.14590998]
 [0.98561894 0.51333524 0.81027503 0.69089169 0.84301146 0.71090439
  0.82505618 0.12210008 0.23111493 0.99816936]
 [0.84550218 0.67823962 0.67797952 0.30207884 0.35943206 0.31892674
  0.18343364 0.22139832 0.3365205  0.89598645]]


#### 56. How to sort an array by the nth column? (★★☆)

In [84]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 1 0]
 [4 1 0]
 [6 7 2]]


#### 57. How to tell if a given 2D array has null columns? (★★☆)

In [87]:
Z = np.random.randint(0,3,(3,10))
Z
print((~Z.any(axis=0)).any())

True


In [ ]:
Z = np.random.randint(0,3,(3,10)).astype(float)
Z[:,0] = np.nan
G = np.isnan(Z)
print((G.all(axis=0)).any())

#### 58. Find the nearest value from a given value in an array (★★☆)

In [90]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(Z)
print(m)

[0.29048083 0.12703844 0.61486574 0.07540806 0.6031896  0.39876621
 0.3927122  0.28195247 0.66071352 0.51139847]
0.5113984747756241


#### 59. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [92]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 60. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [94]:
# Author: Brett Olsen

Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4. 3. 4. 2. 1. 1. 6. 4. 3. 2.]


#### 61. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [95]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 62. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [96]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[2 4 5 2]
   [3 3 1 0]
   [5 4 6 4]]

  [[8 8 4 5]
   [4 6 9 7]
   [5 0 2 1]]

  [[9 9 6 6]
   [3 1 5 5]
   [2 9 8 6]]

  [[0 1 0 7]
   [1 1 0 7]
   [9 2 0 3]]]


 [[[0 9 1 5]
   [0 4 4 5]
   [3 0 1 7]]

  [[3 5 5 4]
   [0 9 8 1]
   [5 9 7 2]]

  [[9 0 8 2]
   [7 9 4 8]
   [2 0 3 2]]

  [[2 6 4 2]
   [7 6 8 6]
   [1 0 7 8]]]


 [[[4 3 7 5]
   [5 3 5 4]
   [2 1 7 6]]

  [[9 4 9 1]
   [0 1 3 5]
   [8 3 5 4]]

  [[4 3 5 4]
   [3 1 5 9]
   [8 5 2 7]]

  [[3 1 0 8]
   [8 7 0 5]
   [5 5 0 6]]]]


#### 63. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

#### 64. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [99]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 65. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [109]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 66. How to swap two rows of an array? (★★★)

In [110]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 67. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [111]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 60) ( 0, 67) ( 1,  4) ( 1,  9) ( 1, 22) ( 1, 43) ( 1, 49) ( 1, 80)
 ( 2,  4) ( 2, 15) ( 4, 15) ( 4, 49) ( 6, 26) ( 6, 88) ( 9, 22) (12, 62)
 (12, 67) (17, 55) (17, 64) (19, 42) (19, 95) (26, 88) (42, 95) (43, 80)
 (55, 64) (60, 67) (61, 74) (61, 83) (62, 67) (74, 83)]


#### 68. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [115]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(C)
print(A)


[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 69. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [119]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

[0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1 1
 1 0 1 0 0 1 1 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 1
 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 0]
[1 1 1 0 1 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 0
 0 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 0 1 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0
 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1]


#### 70. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

#### 71. How to find the most frequent value in an array?

In [123]:
Z = np.random.randint(1,10,50)
print(np.bincount(Z).argmax())

8


#### 72. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [124]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 11 18  1 11]
 [11  1  5  6  5]
 [18  5  3 42 11]
 [ 1  6 42  0 10]
 [11  5 11 10  6]]


#### 73. How to get the n largest values of an array (★★★)

In [126]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 2

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9998 9999]
[9999 9998]


#### 74. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [129]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.86 s ± 321 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
462 ms ± 97.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
508 ms ± 43.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 75. Convert a vector of ints into a matrix binary representation (★★★)

In [131]:

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[  0   1   2   3  15  16  32  64 128]
[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
