# 75 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

#### 4.  How to find the memory size of any array (★☆☆)

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [8]:
x = np.zeros((8,8))
x[::2,1::2] = 1
x[1::2,::2] = 1
x

#trick : Flat :)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [5]:
dt = np.dtype([('r', 'ubyte'), ('g', 'ubyte'), ('b', 'ubyte'), ('a', 'ubyte')])
a = np.array([(-100, 164, 255, 128)], dtype=dt)
a

array([(156, 164, 255, 128)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [11]:
x = np.random.randint(0,15,10)
print(x)
x[(3 < x) & (8 > x)] *= -1
print(x)

[ 6 10  6  5  0  7  0 14  6 14]
[-6 10 -6 -5  0 -7  0 14 -6 14]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [18]:
import numpy as np
import math as mt
mt.log(100,10)
mt.log(100,10)

2.0

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [23]:

a = np.random.uniform(-10,10,10)
print(a)
y =np.ceil(a)
print(y)

[-3.39676059  9.86056153  5.95132147  0.71827432 -6.91063388  7.82880594
  1.16474587 -3.62649141 -8.12049468  3.50444162]
[-3. 10.  6.  1. -6.  8.  2. -3. -8.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [24]:
def int_gen():
    for x in range(10):
        yield x
        
x = np.fromiter(int_gen(), dtype = int, count = -1)
print(x)



[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.fromfunction(lambda i, j: i+j, (5, 2), dtype=np.int8)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. Consider two random array A and B, check if they are equal (★★☆)

#### 42. Make an array immutable (read-only) (★★☆)

In [25]:
x = np.random.uniform(0,10,10)
x.flags.writeable = False
x[1]=3

ValueError: assignment destination is read-only

#### 43. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 44. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 45. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

#### 46. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 47. How to print all the values of an array? (★★☆)

#### 48. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 49. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 50. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 51. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 52. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 53. Generate a generic 2D Gaussian-like array (★★☆)

#### 54. How to randomly place p elements in a 2D array? (★★☆)

#### 55. Subtract the mean of each row of a matrix (★★☆)

#### 56. How to sort an array by the nth column? (★★☆)

#### 57. How to tell if a given 2D array has null columns? (★★☆)

#### 58. Find the nearest value from a given value in an array (★★☆)

#### 59. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 60. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 61. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 62. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 63. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 64. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 65. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 66. How to swap two rows of an array? (★★★)

#### 67. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 68. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 69. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 70. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 71. How to find the most frequent value in an array?

#### 72. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 73. How to get the n largest values of an array (★★★)

#### 74. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 75. Convert a vector of ints into a matrix binary representation (★★★)